import os
import re
import requests
import json
from dotenv import load_dotenv

load_dotenv()

POE_API_KEY = os.getenv("POE_API_KEY")
POE_API_URL = "https://api.poe.com/v1/chat/completions"

DEFAULT_BOT = "gpt-4o-mini"


def extract_json(content: str) -> dict:
    # Remove ```json ... ``` or ``` ... ```
    content = re.sub(r"^```(?:json)?\s*", "", content.strip())
    content = re.sub(r"\s*```$", "", content.strip())

    return json.loads(content)

def generate_resume_content(user_data, bot=DEFAULT_BOT):


    system_prompt = """
    You are a creative AI resume generator for a parody website called
"Super Resume Generator".

Your job is to generate a humorous but coherent resume.

The resume should exaggerate achievements based on a
"competitiveness level" from 0 to 10.

Rules:
- The resume must still read like a resume.
- At low competitiveness, be brutally honest and underwhelming.
- At high competitiveness, become increasingly hyperbolic,
  absurdly confident, and statistically impossible.
- Do NOT mention that this is generated by AI.
- Do NOT explain your reasoning.
- Humor should escalate non-linearly (especially from 7–10).

    Return ONLY valid JSON with these keys:
    name, title, summary, experience, education, skills. If useful information cannot be extracted for relevant keys, fill in none for those keys.
    IMPORTANT OUTPUT CONSTRAINTS (MANDATORY):

You must output data that exactly matches the following schema.
Do not add, remove, rename, or nest fields differently.
Do not include commentary, explanations, markdown, or prose outside the schema.

The output MUST be valid JSON and MUST conform to this structure:

{
  "name": string,
  "title": string,
  "summary": string,
  "experience": [
    {
      "job_title": string,
      "company": string,
      "start_date": string,
      "end_date": string,
      "responsibilities": [string]
    }
  ],
  "education": [
    {
      "degree": string,
      "institution": string,
      "year": string
    }
  ],
  "skills": [string]
}

Rules:
- All fields are required.
- Arrays must not be empty; include at least one item per array.
- Dates may be approximate or fictional but must be strings.
- Humor, exaggeration, and competitiveness should be expressed ONLY in the string values.
- Do NOT introduce new keys such as "achievements", "projects", or "certifications".
- Do NOT collapse arrays into strings.
- Do NOT escape JSON into text; return raw JSON only.
- Ensure the JSON can be parsed by `json.loads()` without modification.

If unsure about content, invent something plausible that fits the tone and schema.
    
    
    """

    user_prompt = f"""
Generate a "super resume" with the following parameters:

Name: {{ name }}
Target Job: {{ target_job }}
Competitiveness Level (0–10): {{ competitiveness }}

Additional user instructions:
{{ custom_prompt }}

Guidelines for competitiveness:

0–2:
- Extremely modest
- Awkward honesty
- Borderline self-sabotaging

3–5:
- Normal resume tone
- Mild confidence
- Slightly polished but believable

6–7:
- Very confident
- Strong achievements
- Stretching reality a little

8–9:
- Over-the-top excellence
- Improbable accomplishments
- Industry-leading claims

10:
- Completely unhinged confidence
- World-altering achievements
- Recruiters should sound lucky to read this
- Still formatted like a resume

Output format:
Return ONLY valid JSON with the following keys:
- name
- title
- summary
- experience
- education
- skills
User data:
    {user_data}
"""

    payload = {
        "model": bot,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.5
    }

    headers = {
        "Authorization": f"Bearer {POE_API_KEY}",
        "Content-Type": "application/json"
    }

    response = requests.post(
        POE_API_URL,
        headers=headers,
        json=payload,
        timeout=30
    )

    response.raise_for_status()

    content = response.json()["choices"][0]["message"]["content"]
    print(f"Raw response: {content}")
    try:
        structured_resume = extract_json(content)
    except json.JSONDecodeError as e:
        raise ValueError("AI did not return valid JSON") from e

    return structured_resume